name: Python package

on: [push]

jobs:
  build:

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]
        platform: [ubuntu-latest] #, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -el {0}
  
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda install gdal
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test
      run: |
        black --check phyghtmap tests
        pytest --mpl
